### ISSUE TITLE
Uploading Zip gives "File type not supported"

### ISSUE THREAD

**Issue by maureenvdr** [gislab-npo/gisquick#50]
Hi
I followed the installation guide on https://gisquick.readthedocs.io/en/latest/administrator-manual/installation/index.html, and i seemed to got things running, but when i upload the prague.zip (again created following the guide)  i get a a 409 conflict error and the message "File type not supported." 
I have tried to find what is going on in the django and server and It seems to fail over the contenttype. 
If i look at the posted form data  it has the Content-Type:"application/x-zip-compressed"
![image](https://user-images.githubusercontent.com/13275724/48002524-18661300-e10c-11e8-8c0d-398b26485256.png)

I am running things on a windows 10 machine in docker version 18.06.1-ce-win73.

I do see that there is a commit to the code 15 days ago("fixed upload of project's zip archive on windows 52dd8d7bf47f97b7c8fe80e23835171cfcb9b3ea), maybe this was because of the same problem i am having? Is this change not yet part of the docker images?

**Comment by marcel-dancak** [comment]
Yes you are right, this issue was fixed few days ago. You can see all available builds of gisquick/django image here https://hub.docker.com/r/gisquick/django/tags/
Only a version with tag 1.0.0 includes this fix, but it has some other issues, like missing link to user profile page... I would be nice to sort out all known issues and build better image.

**Comment by landam** [comment]
This bug was fixed also on demo server. Closing.
