### ISSUE TITLE
`File type not supported.` error on upload (with docker-compose)

### ISSUE THREAD

**Issue by olivierdalang** [gislab-npo/gisquick#78]
Hi !

Just testing on a fresh install with docker-compose, I get a `File type not supported.` error when I try to upload a .zip or .tar.gz. I tried both with master and 1.1.1.

It seems a similar issue was reported already but is marked as fixed : #50 

Details :
`/project/upload`returns a 409 with `{"__all__": [{"message": "File type not supported.", "code": ""}]}`

I didn't see any logs in the output (but think logging is disabled in `example.docker-compose.yml` ?). I tried running with `docker-compose-dev.yml`, but the setup doesn't work (seems static files are not served).

**Comment by marcel-dancak** [comment]
Hi,
`docker-compose-dev.yml` is for local development, when you need to run web application with webpack. And upload is not part of map application, so it wouldn't help you anyway.

Also you are probably trying older docker images due to not up to date documentation/docker-compose example. Upload is currently handled by separate service, which is missing in docs. I will try to update it in the near time.

**Comment by marcel-dancak** [comment]
I have updated example.docker-compose.yml. If you will have your docker-compoe.yml outside of gisquick repository, you will need to copy nginx config from https://github.com/gislab-npo/gisquick/tree/master/docker/nginx-conf

Let me know if it will work for you.

**Comment by marcel-dancak** [comment]
Deployment has changed a lot since this report. Also I didn't encounter any issues with upload for a long time.

There was several reports in older 1.x version, but this is not maintained anymore, so I'm closing this issue.
