### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by JanBednarik** [gislab-npo/gisquick#92]
I'm trying to run Gisquick using Docker Compose but [installation instructions](https://gisquick.readthedocs.io/en/latest/administrator-manual/installation/docker.html) are outdated. Images in docker hub are not versioned and seems like they diverged from expected versions in documentation.

Can you update installation instructions please? And can you start versioning releases, Docker images and documentation, so it will not diverge in the future please?

**Comment by marcel-dancak** [comment]
I will update README with info about different versions. There is basically legacy version 1.x, which is not going to be updated, because it's based on quite old tech stack. But unfortunately current documentation was written only for it, and new version is not finished yet.

Latest version doesn't have any tag or release, and until there will be a very good reason to do so, there will be only this latest version (aka rolling release system). This version shouldn't be hard to run, you will just need use https://github.com/gislab-npo/gisquick-cli

**Comment by JanBednarik** [comment]
Thank you, we will try CLI.
